"""Export the world to artifacts: the web visualization data and README stats.

The web viewer is fully static (openable via ``file://``), so instead of having
the page fetch JSON, we write the world into ``web/world.js`` as a global. This
keeps the visualization dependency-free and works anywhere.
"""

from __future__ import annotations

import json
import os
from typing import Any

from . import world as worldmod
from .simulation import living, _age_years


def export_web(world: dict[str, Any]) -> str:
    path = os.path.join(worldmod.root(), "web", "world.js")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload = json.dumps(world, ensure_ascii=False)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by claudetown.render -- do not edit by hand.\n")
        fh.write("window.WORLD = ")
        fh.write(payload)
        fh.write(";\n")
    return path


def _oldest(world):
    alive = living(world)
    return max(alive, key=lambda c: c["age_months"]) if alive else None


def _biggest_family(world):
    counts: dict[str, int] = {}
    for c in living(world):
        counts[c["surname"]] = counts.get(c["surname"], 0) + 1
    if not counts:
        return None, 0
    name = max(counts, key=counts.get)
    return name, counts[name]


def update_readme(world: dict[str, Any]) -> None:
    """Refresh the live-stats block in README.md between sentinel markers."""
    path = os.path.join(worldmod.root(), "README.md")
    if not os.path.exists(path):
        return
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()

    start = "<!-- TOWN-STATS:START -->"
    end = "<!-- TOWN-STATS:END -->"
    if start not in text or end not in text:
        return

    alive = living(world)
    pop = len(alive)
    born = len(world["citizens"])
    dead = born - pop
    oldest = _oldest(world)
    fam, fam_n = _biggest_family(world)
    employed = sum(1 for c in alive if c["job"])
    year, _ = worldmod.date_parts(world["tick"])

    block = [
        start,
        "",
        f"**{world['name']}** &nbsp;·&nbsp; *{worldmod.date_str(world['tick'])}* "
        f"&nbsp;·&nbsp; founded {world['founded']}",
        "",
        "| Metric | Value |",
        "|:--|:--|",
        f"| Population (living) | **{pop}** |",
        f"| Souls ever recorded | {born} ({dead} at rest) |",
        f"| Buildings | {len(world['buildings'])} |",
        f"| Treasury | {world['treasury']} coins |",
        f"| Employed | {employed} of {pop} |",
        f"| Years simulated | {year + 1} |",
    ]
    if oldest:
        block.append(f"| Eldest resident | {oldest['name']}, age {_age_years(oldest)} |")
    if fam:
        block.append(f"| Largest family | the {fam}s ({fam_n}) |")
    block += [
        "",
        "_Stats and the map under `web/` regenerate every time the town advances._",
        "",
        end,
    ]

    new = text[: text.index(start)] + "\n".join(block) + text[text.index(end) + len(end):]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)


def export_all(world: dict[str, Any]) -> None:
    export_web(world)
    update_readme(world)
