/* ClaudeTown viewer -- dependency-free rendering of window.WORLD. */
(function () {
  "use strict";
  const W = window.WORLD;
  const MONTHS = ["Frostwane","Thawmoon","Seedfall","Bloomtide","Sunhigh","Hayrest",
                  "Goldmaize","Emberfall","Mistgather","Leafdown","Snowcome","Yuleweald"];
  const SVGNS = "http://www.w3.org/2000/svg";

  if (!W) { document.getElementById("town-sub").textContent = "No world data found."; return; }

  const living = Object.values(W.citizens).filter(c => c.alive);
  const dateStr = t => `${MONTHS[t % 12]}, Year ${Math.floor(t / 12) + 1}`;

  // Deterministic PRNG (mulberry32) for stable map layout from a building id.
  function rngFrom(seed) {
    let a = seed >>> 0;
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  // ---- Header -------------------------------------------------------------
  document.getElementById("town-name").textContent = W.name;
  document.getElementById("town-sub").textContent =
    `${dateStr(W.tick)} · founded ${W.founded} · "where the chronicle never ends"`;

  const everN = Object.keys(W.citizens).length;
  const stats = [
    ["Population", living.length],
    ["Buildings", Object.keys(W.buildings).length],
    ["Treasury", W.treasury + "c"],
    ["Years", Math.floor(W.tick / 12) + 1],
    ["Souls recorded", everN],
  ];
  const strip = document.getElementById("stat-strip");
  stats.forEach(([k, v]) => {
    const d = document.createElement("div");
    d.className = "stat";
    d.innerHTML = `<b>${v}</b><span>${k}</span>`;
    strip.appendChild(d);
  });
  document.getElementById("foot").textContent =
    `Seed ${W.seed} · generated by the ClaudeTown engine · ${everN} lives chronicled`;

  // ---- Tabs ---------------------------------------------------------------
  document.querySelectorAll(".tabs button").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tabs button").forEach(b => b.classList.remove("active"));
      document.querySelectorAll(".tab-panel").forEach(p => p.classList.remove("active"));
      btn.classList.add("active");
      document.getElementById("tab-" + btn.dataset.tab).classList.add("active");
    });
  });

  // ---- Map ----------------------------------------------------------------
  const ICON = {
    house: "#c9a36a", farm: "#7fae5b", well: "#5ea9c9", market: "#e0a04a",
    smithy: "#b06b4a", tavern: "#d98e54", mill: "#bcae8a", temple: "#cfc0e0",
    school: "#7fb0d8", library: "#8fb89a", town_hall: "#e0c45a", observatory: "#9aa6e0",
    theatre: "#d987b0",
  };
  function drawMap() {
    const wrap = document.getElementById("map-wrap");
    const w = 900, h = 540;
    const svg = el("svg", { viewBox: `0 0 ${w} ${h}` });
    svg.appendChild(el("rect", { x: 0, y: 0, width: w, height: h, fill: "#20233a", rx: 10 }));
    // a meandering river
    let path = `M 0 ${h * 0.7}`;
    const r = rngFrom((W.seed ^ 0x9e37) >>> 0);
    for (let x = 0; x <= w; x += 90)
      path += ` Q ${x + 45} ${h * 0.7 + (r() - 0.5) * 120} ${x + 90} ${h * 0.66 + (r() - 0.5) * 90}`;
    svg.appendChild(el("path", { d: path, fill: "none", stroke: "#3a6e86",
      "stroke-width": 14, opacity: 0.5, "stroke-linecap": "round" }));

    const blds = Object.values(W.buildings).sort((a, b) => a.founded_tick - b.founded_tick);
    blds.forEach(b => {
      const rr = rngFrom((parseInt(b.id, 10) * 2654435761) >>> 0);
      const civic = !["house", "farm"].includes(b.type);
      const cx = w / 2 + (rr() - 0.5) * (civic ? w * 0.45 : w * 0.85);
      const cy = h * 0.42 + (rr() - 0.5) * (civic ? h * 0.5 : h * 0.8);
      const g = el("g", {});
      const color = ICON[b.type] || "#aaa";
      const size = civic ? 26 : (b.type === "farm" ? 30 : 18);
      drawBuilding(g, cx, cy, size, color, b.type);
      const label = el("text", { x: cx, y: cy + size + 11, "text-anchor": "middle", class: "bld-label" });
      label.textContent = b.name.length > 22 ? b.type : b.name;
      g.appendChild(label);
      const title = el("title", {});
      const staff = (b.workers || []).filter(id => W.citizens[id] && W.citizens[id].alive)
        .map(id => W.citizens[id].name);
      const homeN = (b.residents || []).filter(id => W.citizens[id] && W.citizens[id].alive).length;
      title.textContent = `${b.name} (${b.type})\nFounded ${dateStr(b.founded_tick)}` +
        (staff.length ? `\nStaff: ${staff.join(", ")}` : "") +
        (homeN ? `\nHome to ${homeN}` : "");
      g.appendChild(title);
      svg.appendChild(g);
    });
    wrap.innerHTML = "";
    wrap.appendChild(svg);
  }

  function drawBuilding(g, x, y, s, color, type) {
    if (type === "farm") {
      g.appendChild(el("rect", { x: x - s, y: y - s * 0.6, width: s * 2, height: s * 1.2, fill: "#3c5a32", rx: 3 }));
      for (let i = -2; i <= 2; i++)
        g.appendChild(el("line", { x1: x - s, y1: y + i * 4, x2: x + s, y2: y + i * 4, stroke: color, "stroke-width": 1.5, opacity: 0.7 }));
      return;
    }
    if (type === "well") {
      g.appendChild(el("circle", { cx: x, cy: y, r: s * 0.55, fill: color }));
      g.appendChild(el("circle", { cx: x, cy: y, r: s * 0.3, fill: "#20233a" }));
      return;
    }
    g.appendChild(el("rect", { x: x - s * 0.6, y: y - s * 0.2, width: s * 1.2, height: s * 0.9, fill: color, rx: 2 }));
    g.appendChild(el("polygon", { points: `${x - s * 0.75},${y - s * 0.2} ${x},${y - s * 0.75} ${x + s * 0.75},${y - s * 0.2}`, fill: shade(color, -25) }));
    if (["temple", "town_hall", "observatory", "library", "theatre"].includes(type))
      g.appendChild(el("rect", { x: x - 2, y: y - s * 1.1, width: 4, height: s * 0.35, fill: shade(color, 30) }));
  }

  // ---- Charts -------------------------------------------------------------
  function drawCharts() {
    const host = document.getElementById("charts");
    host.innerHTML = "";
    const series = [
      ["Population", W.timeseries.population, "#6db4a8"],
      ["Treasury", W.timeseries.treasury, "#f2c94c"],
      ["Average mood", W.timeseries.avg_mood, "#e08099"],
    ];
    series.forEach(([title, data, color]) => host.appendChild(lineChart(title, data, color)));
    host.appendChild(barChart("Births & deaths per month", W.timeseries.births, W.timeseries.deaths));
  }

  function lineChart(title, data, color) {
    const w = 880, h = 180, pad = 30;
    const svg = el("svg", { viewBox: `0 0 ${w} ${h}` });
    const t = el("text", { x: pad, y: 16, class: "chart-title" }); t.textContent = title; svg.appendChild(t);
    if (!data || !data.length) return svg;
    const max = Math.max(...data, 1), min = Math.min(...data, 0);
    const xs = i => pad + (i / Math.max(1, data.length - 1)) * (w - pad * 2);
    const ys = v => (h - pad) - ((v - min) / Math.max(1, max - min)) * (h - pad - 24);
    svg.appendChild(el("line", { x1: pad, y1: h - pad, x2: w - pad, y2: h - pad, class: "axis" }));
    let d = "";
    data.forEach((v, i) => d += `${i === 0 ? "M" : "L"} ${xs(i).toFixed(1)} ${ys(v).toFixed(1)} `);
    svg.appendChild(el("path", { d: d + `L ${xs(data.length - 1)} ${h - pad} L ${xs(0)} ${h - pad} Z`, fill: color, opacity: 0.12 }));
    svg.appendChild(el("path", { d, fill: "none", stroke: color, "stroke-width": 2 }));
    const lab = el("text", { x: w - pad, y: 16, class: "axis-label", "text-anchor": "end" });
    lab.textContent = `now: ${data[data.length - 1]}  ·  peak: ${max}`;
    svg.appendChild(lab);
    return svg;
  }

  function barChart(title, births, deaths) {
    const w = 880, h = 180, pad = 30;
    const svg = el("svg", { viewBox: `0 0 ${w} ${h}` });
    const t = el("text", { x: pad, y: 16, class: "chart-title" }); t.textContent = title; svg.appendChild(t);
    births = births || []; deaths = deaths || [];
    const n = births.length;
    const max = Math.max(1, ...births, ...deaths);
    const bw = (w - pad * 2) / Math.max(1, n);
    const mid = (h - pad);
    for (let i = 0; i < n; i++) {
      const bh = (births[i] / max) * (h / 2 - 20);
      const dh = (deaths[i] / max) * (h / 2 - 20);
      if (births[i]) svg.appendChild(el("rect", { x: pad + i * bw, y: mid - bh, width: Math.max(1, bw * 0.8), height: bh, fill: "#6db4a8" }));
      if (deaths[i]) svg.appendChild(el("rect", { x: pad + i * bw, y: mid, width: Math.max(1, bw * 0.8), height: dh, fill: "#e08099" }));
    }
    svg.appendChild(el("line", { x1: pad, y1: mid, x2: w - pad, y2: mid, class: "axis" }));
    return svg;
  }

  // ---- People -------------------------------------------------------------
  const grid = document.getElementById("people-grid");
  function renderPeople() {
    const q = document.getElementById("people-search").value.toLowerCase();
    const showDead = document.getElementById("show-dead").checked;
    let people = Object.values(W.citizens);
    if (!showDead) people = people.filter(c => c.alive);
    if (q) people = people.filter(c => c.name.toLowerCase().includes(q));
    people.sort((a, b) => (a.alive === b.alive ? b.age_months - a.age_months : (a.alive ? -1 : 1)));
    grid.innerHTML = "";
    people.slice(0, 200).forEach(c => grid.appendChild(personCard(c)));
    if (!people.length) grid.innerHTML = "<p class='hint'>No one by that name.</p>";
  }
  function personCard(c) {
    const d = document.createElement("div");
    d.className = "person" + (c.alive ? "" : " dead");
    const age = Math.floor(c.age_months / 12);
    const partner = c.partner && W.citizens[c.partner] ? W.citizens[c.partner].name : null;
    const job = c.job ? `${c.job}` : "no trade";
    let rel = "";
    if (partner) rel += `Wed to ${partner}. `;
    if (c.children && c.children.length) rel += `${c.children.length} child(ren). `;
    if (c.friends && c.friends.length) rel += `${c.friends.length} friend(s). `;
    if (c.rivals && c.rivals.length) rel += `${c.rivals.length} rival(s).`;
    d.innerHTML =
      `<h3>${c.name}</h3>` +
      `<div class="meta">${c.alive ? "age " + age : "lived to " + age + " — " + (c.epitaph || "")} · ${job}</div>` +
      `<div class="traits">${(c.traits || []).map(t => `<span>${t}</span>`).join("")}</div>` +
      `<div class="rel">${rel || "&nbsp;"}</div>` +
      (c.alive ? bars(c) : "");
    return d;
  }
  function bars(c) {
    const row = (label, v, color) =>
      `<div class="bar" title="${label} ${v}"><i style="width:${Math.max(0, Math.min(100, v))}%;background:${color}"></i></div>`;
    return `<div class="bars">${row("mood", c.mood, "#f2c94c")}${row("health", c.health, "#6db4a8")}</div>`;
  }
  document.getElementById("people-search").addEventListener("input", renderPeople);
  document.getElementById("show-dead").addEventListener("change", renderPeople);

  // ---- History ------------------------------------------------------------
  function renderHistory() {
    const tl = document.getElementById("timeline");
    tl.innerHTML = "";
    [...W.history].reverse().forEach(ev => {
      const d = document.createElement("div");
      d.className = "tl-item kind-" + ev.kind;
      d.innerHTML = `<div class="date">${dateStr(ev.tick)} · ${ev.kind}</div><div>${ev.text}</div>`;
      tl.appendChild(d);
    });
    if (!W.history.length) tl.innerHTML = "<p class='hint'>No history yet.</p>";
  }

  // ---- helpers ------------------------------------------------------------
  function el(name, attrs) {
    const e = document.createElementNS(SVGNS, name);
    for (const k in attrs) e.setAttribute(k, attrs[k]);
    return e;
  }
  function shade(hex, amt) {
    const n = parseInt(hex.slice(1), 16);
    let r = (n >> 16) + amt, g = ((n >> 8) & 255) + amt, b = (n & 255) + amt;
    r = Math.max(0, Math.min(255, r)); g = Math.max(0, Math.min(255, g)); b = Math.max(0, Math.min(255, b));
    return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, "0")}`;
  }

  drawMap(); drawCharts(); renderPeople(); renderHistory();
})();
